### PR TITLE
Fix detekt's SwallowedException warnings

### PR DESCRIPTION
**Pull request by jtraglia**
This PR fixes the two [SwallowedException](https://detekt.dev/exceptions.html#swallowedexception) warnings. 

> Exceptions should not be swallowed. This rule reports all instances where exceptions are `caught` and not correctly passed (e.g. as a cause) into a newly thrown exception.

* For `MultiaddrDns`, I think it is suitable to `log.debug` the exception; might help if someone is having DNS issues.
* The `AsyncExt` methods are meant to unwrap `ExecutionException` so I just suppressed the warnings here.

### CODE REVIEW

**Comment by jtraglia** [comment]
If #236 is merged prior to this PR, we should delete the baseline file & the baseline configuration line.

**Review by Nashatyrev — APPROVED** [review]
LGTM

**Comment by jtraglia** [comment]
Hey @Nashatyrev, could you merge this PR and #236 for me?

**Comment by Nashatyrev** [comment]
Will fix the conflict on Monday. 
Sorry for delay with this PR

**Comment by jtraglia** [comment]
Hey there, no worries! I fixed the conflict. Neither of these PRs were important.

**Pull request merged**
