### PR TITLE
Implement autonat protocol

### PR DESCRIPTION
**Pull request by ianopolous**
@Nashatyrev Any thoughts on this?

### CODE REVIEW

**Comment by Nashatyrev** [comment]
I'm pretty fine with it, assuming there are just new classes added. 
@StefanBratanov what do you think?

**Comment by ianopolous** [comment]
(Next up will be dcutr and integrating all these into RelayTransport)

**Comment by StefanBratanov** [comment]
LGTM to me as well

**Comment by ianopolous** [comment]
Tests were green before the rebase off develop. Are they flakey?

**Comment by ianopolous** [comment]
This is good to merge now.

**Comment by ianopolous** [comment]
@Nashatyrev Any chance of merging this? We have downstream work that depends on it.

**Comment by StefanBratanov** [comment]
> @Nashatyrev Any chance of merging this? We have downstream work that depends on it.

Just did. Sorry for the delay.

**Pull request merged**
