### PR TITLE
Set topicID on outbound IHAVE and ignore inbound IHAVE for unknown topic

### PR DESCRIPTION
**Pull request by StefanBratanov**
fixes https://github.com/libp2p/jvm-libp2p/issues/361

### CODE REVIEW

**Comment by Nashatyrev** [comment]
I think we would need to group `IHAVE`s in the resulting message produced by `GossipRpcPartsQueue` else we might get significant message size overhead

**Comment by Nashatyrev** [comment]
Please check here: https://github.com/StefanBratanov/jvm-libp2p/pull/1
Fixing the case has also addressed the grouping question

**Comment by StefanBratanov** [comment]
> Please check here: [StefanBratanov#1](https://github.com/StefanBratanov/jvm-libp2p/pull/1) Fixing the case has also addressed the grouping question

Thanks. I agree with the change. I have missed that part. Thanks.

**Comment by Nashatyrev** [comment]
Added another minor improvement

**Review by Nashatyrev — APPROVED** [review]
LGTM

**Pull request merged**
