### PR TITLE
Example/chat

### PR DESCRIPTION
**Pull request by jezhiggins**
Simple peer-to-peer chat example.

- uses MDNS-SD to find peers on the local network
- demonstrates building a simple protocol interacting with UI components
- has both command-line and Android client applications
- protocol compiled into a jar file used by both applications

### CODE REVIEW

**Comment by jezhiggins** [comment]
Running on a Mac

image

**Comment by jezhiggins** [comment]
Running on an Ubuntu Linux box 

image

**Comment by jezhiggins** [comment]
And running on an Android phone 

image

**Comment by Nashatyrev** [comment]
Super 👍

**Pull request merged**
